### PR TITLE
Modify brokenState and ways of extracting pname&version in ETL process

### PR DESCRIPTION
**Pull request by zz1874**
Here are two minor changes in the ETL process.
- For some packages, the `brokenState` of them is an empty string `''`, which conflicts with the `boolean` format, so we turn the `brokenState` property into `str`.
- Suggested by @jlesquembre's talk with nix group: The queries use `pname` and `version`, but some derivations only have a `name` attribute. We use nix builtin function `builtins.parseDrvName` to get the name on all cases.

### CODE REVIEW

**Comment by GuillaumeDesforges** [comment]
What does `brokenState` mean? Would an empty string mean a `False`?

Good thinking on `parseDrvName` 💯

**Comment by dorranh** [comment]
PS: I'll leave the review of the nix logic to @jlesquembre or @GuillaumeDesforges, but one thing which stood out to me in this PR is that we currently don't have a way of testing the logic for extracting data from Nix. An interesting feature could be to allow for the specification of an attribute or similar so that we can run integration tests which extract a small, known set of dependencies from Nix to ensure the business logic for getting package properties works. Or alternatively there might also be some ways of unit testing Nix code which I'm unaware of :thinking:

**Comment by zz1874** [comment]
> What does `brokenState` mean? Would an empty string mean a `False`?

@GuillaumeDesforges That's a good question! The package will be marked as `broken` and has had its `meta.broken` set to `true`. For the packages whose `brokenState` is an empty string, their `meta` currently don't have a `broken` attribute.

I'll ensure if an empty string means `false` next week :ok_hand:

**Review by jlesquembre — APPROVED** [review]
I tested it locally, it looks good to me

**Pull request merged**
