### PR TITLE
To nixtract [diff only, do not merge]

### PR DESCRIPTION
**Pull request by GuillaumeDesforges**
As discussed with @dorranh, let's focus first on releasing a good tool to extract the graph data.

This PR
- removes the backend
- removes the frontend
- lifts the extraction to the top level
- renames to "nixtract"

### CODE REVIEW

**Review by dorranh — COMMENTED** [review]
In general I think this plan for dividing up the project looks good. Just one question: Is there a specific reason for the move to GitHub Actions-provided packages in CI as opposed to using the linting commands in the Nix flake?

**Comment by GuillaumeDesforges** [comment]
> Is there a specific reason for the move to GitHub Actions-provided packages in CI as opposed to using the linting commands in the Nix flake?

None, I just took a template.
All the dev tools are provided by poetry so they are locked. They don't require any system deps as well, so I didn't see a need to change.

**Comment by dorranh** [comment]
@GuillaumeDesforges, nice, this is looking good to me! As noted separately, this PR is intended purely to demonstrate the diff splitting off the extraction portion of the codebase which is intended to be managed as a separate project. Please close this when you're ready and link to the new repository whenever we've finished the migration.

**Comment by GuillaumeDesforges** [comment]
Let's move on then

**Pull request closed without merging**
